SECRET_KEY='dev'
MYSQL_HOST = 'localhost'
MYSQL_USER = 'ivy'
MYSQL_PASSWORD = ''
MYSQL_DB = 'lucaflect01'
SITENAME = 'Lucaflect Dev'

ALLOW_REGISTRATION = True
REGISTRATION_KEY = ''
TEMPLATES_AUTO_RELOAD = True

UPLOAD_FOLDER='uploads'
MAX_CONTENT_LENGTH= 5 * 1024 * 1024
IMGTYPES=['.gif','.png','.jpg','.jpeg']