DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS comic;
CREATE TABLE user (user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, username VARCHAR(20) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, join_date DATE, email VARCHAR(255), social_media TEXT);
CREATE TABLE comic (comic_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, author_id INTEGER NOT NULL, posted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, draft TINYINT(1) DEFAULT 0, FOREIGN KEY (author_id) REFERENCES user (user_id));